[book]
title = "Smart Vaults Book"
description = "Description"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/smartvaults/book"
edit-url-template = "https://github.com/smartvaults/book/edit/master/{path}"
